cmd_Release/obj.target/validation/src/validation.o := /build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/bin/ccache /usr/bin/gcc -o Release/obj.target/validation/src/validation.o ../src/validation.c '-DNODE_GYP_MODULE_NAME=validation' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/include/node -I/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/src -I/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/deps/openssl/config -I/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/deps/openssl/openssl/include -I/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/deps/uv/include -I/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/deps/zlib -I/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -std=c99 -m64 -O3 -fno-omit-frame-pointer  -MMD -MF ./Release/.deps/Release/obj.target/validation/src/validation.o.d.raw -I/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/include -O2 -I/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/include -c
Release/obj.target/validation/src/validation.o: ../src/validation.c \
 /build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/include/node/node_api.h \
 /build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/include/node/js_native_api.h \
 /build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/include/node/js_native_api_types.h \
 /build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/include/node/node_api_types.h
../src/validation.c:
/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/include/node/node_api.h:
/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/include/node/js_native_api.h:
/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/include/node/js_native_api_types.h:
/build/buildroot/output/cvitek_CV181X_glibc_riscv64/per-package/nanokvm-server/host/usr/include/node/node_api_types.h:
